# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: astral-sh.ty
PackageVersion: 0.0.1-alpha.23
PackageLocale: en-US
Publisher: Astral Software Inc.
PublisherUrl: https://astral.sh/
PublisherSupportUrl: https://github.com/astral-sh/ty/issues
Author: Astral Software Inc.
PackageName: ty
PackageUrl: https://github.com/astral-sh/ty
License: MIT
LicenseUrl: https://github.com/astral-sh/ty/blob/HEAD/LICENSE
Copyright: Copyright (c) 2025 Astral Software Inc.
CopyrightUrl: https://github.com/astral-sh/ty/blob/HEAD/LICENSE
ShortDescription: An extremely fast Python type checker and language server, written in Rust.
Moniker: ty
Tags:
- python
ReleaseNotes: |-
  Release Notes
  Released on 2025-10-16.
  Bug fixes
  - Fix handling of dataclass field()s without default values (#20914)
  - Fix false-positive diagnostics on super() calls (#20814, #20843)
  - Fix match pattern value narrowing to use equality semantics (#20882)
  - Fix "missing root" panic when handling completion requests (#20917)
  - Fix overwriting of declared base class attributes through undeclared subclass members (#20764)
  - Fix runaway execution time for mutually referential instance attributes (#20645)
  CLI
  - For unresolved-import diagnostics, limit the shown import paths to at most five, unless in verbose mode (#20912)
  - Write files that are slow to type check to log output (#20836)
  - Remove "pre-release software" warning (#20817)
  LSP server
  - Improve ranking of autocomplete suggestions (#20807)
  Type inference and diagnostics
  - Use return type annotations as context for bidirectional type inference (#20528)
  - Use bidirectional type context for TypedDict construction (#20806)
  - Add support for unpacking of heterogeneous tuples in unions (#20377)
  - Add a new diagnostic for generic classes that reference typevars from an enclosing scope (#20822)
  - Add hint when accessing standard library module attributes that are not available on the configured Python version (#20909)
  - Treat functions, methods, and dynamic types as function-like Callables (#20842)
  - Treat Callables as bound-method descriptors in special cases (#20802)
  - Treat Callable dunder members as bound method descriptors (#20860)
  - Sync vendored typeshed stubs (#20876). Typeshed diff
  Performance improvements
  - Improve performance by caching union simplification type relations (#20477)
  Contributors
  - @mtshiba
  - @AlexWaygood
  - @ericmarkmartin
  - @carljm
  - @ntBre
  - @sharkdp
  - @BurntSushi
  - @Gankra
  - @MichaReiser
  - @dcreager
  Install ty 0.0.1-alpha.23
  Install prebuilt binaries via shell script
  curl --proto '=https' --tlsv1.2 -LsSf https://github.com/astral-sh/ty/releases/download/0.0.1-alpha.23/ty-installer.sh | sh
  Install prebuilt binaries via powershell script
  powershell -ExecutionPolicy Bypass -c "irm https://github.com/astral-sh/ty/releases/download/0.0.1-alpha.23/ty-installer.ps1 | iex"
  Download ty 0.0.1-alpha.23
  ─────────────────────────────────────────────┬────────────────────────────┬─────────────
  File                                         │Platform                    │Checksum
  ─────────────────────────────────────────────┼────────────────────────────┼─────────────
  ty-aarch64-apple-darwin.tar.gz               │Apple Silicon macOS         │checksum
  ─────────────────────────────────────────────┼────────────────────────────┼─────────────
  ty-x86_64-apple-darwin.tar.gz                │Intel macOS                 │checksum
  ─────────────────────────────────────────────┼────────────────────────────┼─────────────
  ty-aarch64-pc-windows-msvc.zip               │ARM64 Windows               │checksum
  ─────────────────────────────────────────────┼────────────────────────────┼─────────────
  ty-i686-pc-windows-msvc.zip                  │x86 Windows                 │checksum
  ─────────────────────────────────────────────┼────────────────────────────┼─────────────
  ty-x86_64-pc-windows-msvc.zip                │x64 Windows                 │checksum
  ─────────────────────────────────────────────┼────────────────────────────┼─────────────
  ty-aarch64-unknown-linux-gnu.tar.gz          │ARM64 Linux                 │checksum
  ─────────────────────────────────────────────┼────────────────────────────┼─────────────
  ty-i686-unknown-linux-gnu.tar.gz             │x86 Linux                   │checksum
  ─────────────────────────────────────────────┼────────────────────────────┼─────────────
  ty-powerpc64-unknown-linux-gnu.tar.gz        │PPC64 Linux                 │checksum
  ─────────────────────────────────────────────┼────────────────────────────┼─────────────
  ty-powerpc64le-unknown-linux-gnu.tar.gz      │PPC64LE Linux               │checksum
  ─────────────────────────────────────────────┼────────────────────────────┼─────────────
  ty-s390x-unknown-linux-gnu.tar.gz            │S390x Linux                 │checksum
  ─────────────────────────────────────────────┼────────────────────────────┼─────────────
  ty-x86_64-unknown-linux-gnu.tar.gz           │x64 Linux                   │checksum
  ─────────────────────────────────────────────┼────────────────────────────┼─────────────
  ty-armv7-unknown-linux-gnueabihf.tar.gz      │ARMv7 Linux                 │checksum
  ─────────────────────────────────────────────┼────────────────────────────┼─────────────
  ty-aarch64-unknown-linux-musl.tar.gz         │ARM64 MUSL Linux            │checksum
  ─────────────────────────────────────────────┼────────────────────────────┼─────────────
  ty-i686-unknown-linux-musl.tar.gz            │x86 MUSL Linux              │checksum
  ─────────────────────────────────────────────┼────────────────────────────┼─────────────
  ty-x86_64-unknown-linux-musl.tar.gz          │x64 MUSL Linux              │checksum
  ─────────────────────────────────────────────┼────────────────────────────┼─────────────
  ty-arm-unknown-linux-musleabihf.tar.gz       │ARMv6 MUSL Linux (Hardfloat)│checksum
  ─────────────────────────────────────────────┼────────────────────────────┼─────────────
  ty-armv7-unknown-linux-musleabihf.tar.gz     │ARMv7 MUSL Linux            │checksum
  ─────────────────────────────────────────────┴────────────────────────────┴─────────────
ReleaseNotesUrl: https://github.com/astral-sh/ty/releases/tag/0.0.1-alpha.23
Documentations:
- DocumentLabel: Docs
  DocumentUrl: https://docs.astral.sh/ty/
ManifestType: defaultLocale
ManifestVersion: 1.10.0
