# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Dystroy.broot
PackageVersion: 1.52.0
PackageLocale: en-US
Publisher: Dystroy
PublisherUrl: https://dystroy.org/broot/
PublisherSupportUrl: https://github.com/Canop/broot/issues
PackageName: Broot
PackageUrl: https://github.com/Canop/broot
License: MIT
LicenseUrl: https://github.com/Canop/broot/blob/HEAD/LICENSE
ShortDescription: A new way to see and navigate directory trees.
Tags:
- cli
- command-line
- rust
ReleaseNotes: |-
  - auto_open_staging_area preference - Fix #1090
  - search content of file target of symlink - Fix #1081
  - fix nushell script (swapped logic for --listen and --listen-auto) - Thanks @cderwin
  - return non-zero exit code on error - Thanks @Sambhram1
ReleaseNotesUrl: https://github.com/Canop/broot/releases/tag/v1.52.0
ManifestType: defaultLocale
ManifestVersion: 1.10.0
