# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: VoodooSoft.DefenderUI
PackageVersion: '1.45'
PackageLocale: en-US
Publisher: VoodooSoft, LLC
PublisherUrl: https://voodooshield.com/
PrivacyUrl: https://voodooshield.com/Privacy.aspx
Author: VoodooSoft, LLC
PackageName: DefenderUI
PackageUrl: https://www.cyberlock.tech/defenderui.html
License: Proprietary
LicenseUrl: https://voodooshield.com/Terms.aspx
Copyright: © 2024 - DefenderUI
ShortDescription: A better UI for Microsoft Defender
Description: Microsoft Defender needed a better UI, so we built one. DefenderUI significantly improves usability & unlocks many hidden security features of Microsoft Defender. Compatible with Windows 10 / 11 & truly free.
Tags:
- antivirus
- defender
- microsoft-defender
- security
- windows-defender
ManifestType: defaultLocale
ManifestVersion: 1.10.0
