# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: VoodooSoft.DefenderUI
PackageVersion: '1.45'
InstallerLocale: en-US
InstallerType: inno
Scope: machine
UpgradeBehavior: install
ProductCode: '{D60974B4-94D2-4A22-A4B9-4C2E0E264B7B}_is1'
ReleaseDate: 2025-10-27
AppsAndFeaturesEntries:
- ProductCode: '{D60974B4-94D2-4A22-A4B9-4C2E0E264B7B}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\DefenderUI'
Installers:
- Architecture: x86
  InstallerUrl: https://www.cyberlock.tech/downloads/InstallDefenderUI.exe
  InstallerSha256: 00C6072AC0683EAA228A382B2EFD654D4261CC4F9FE77EB64AC00BE3310DFEC1
ManifestType: installer
ManifestVersion: 1.10.0
