# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Balena.BalenaCLI
PackageVersion: 22.4.16
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- balena
ProductCode: balena-cli
ReleaseDate: 2025-10-30
AppsAndFeaturesEntries:
- ProductCode: balena-cli
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\balena-cli'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/balena-io/balena-cli/releases/download/v22.4.16/balena-cli-v22.4.16-windows-x64-installer.exe
  InstallerSha256: 8AEDD36C82C62E98C8530BD7E485B60C6009075B4C4F71E133AEA355ED2E779C
ManifestType: installer
ManifestVersion: 1.10.0
