# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: GoACME.lego
PackageVersion: 4.27.0
PackageLocale: en-US
Publisher: Sebastian Erhart
PublisherUrl: https://go-acme.github.io/lego
PublisherSupportUrl: https://github.com/go-acme/lego/issues
Author: Sebastian Erhart
PackageName: Lego
PackageUrl: https://github.com/go-acme/lego
License: MIT
LicenseUrl: https://github.com/go-acme/lego/blob/HEAD/LICENSE
Copyright: Copyright (c) Sebastian Erhart
CopyrightUrl: https://github.com/go-acme/lego/blob/master/LICENSE
ShortDescription: Let's Encrypt/ACME client and library written in Go
Moniker: lego
Tags:
- acme
- acme-client
- certificate
- dns
- letsencrypt
- rfc8555
- rfc8737
- rfc8738
- security
- tls
ReleaseNotes: |-
  lego is an independent, free, and open-source project, if you value it, consider supporting it! ❤️
  Everybody thinks that the others will donate, but in the end, nobody does.
  So if you think that lego is worth it, please consider donating.
  For key updates, see the changelog.
  Changelog
  - f432d21 Add DNS provider for Hostinger (#2651)
  - 621d9d0 Add DNS provider for Beget.com (#1879)
  - a3f3c62 Add DNS provider for Octenium (#2661)
  - 0fcac85 docs: improve changelog headings
  - acfb5ea docs: sponsor incentives
  - ba156d5 feat: support --private-key with a PKCS#8 keypair (#2653)
  - 8249f73 fix: deduplicate order identifiers (#2656)
  - f0c314c hetzner: update to new API (#2663)
  - 95eb44c hostinger: fix Present (#2654)
  - 26920e7 otc: add example (#2655)
  - bf0e89c otc: adds option to use private zone (#2649)
ReleaseNotesUrl: https://github.com/go-acme/lego/releases/tag/v4.27.0
ManifestType: defaultLocale
ManifestVersion: 1.10.0
