# Created with WinGet Releaser using komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Jackett.Jackett
PackageVersion: 0.24.241
PackageLocale: en-US
Publisher: Jackett
PublisherUrl: https://github.com/Jackett/Jackett
PublisherSupportUrl: https://github.com/Jackett/Jackett/issues
Author: Jackett Contributors
PackageName: Jackett
PackageUrl: https://github.com/Jackett/Jackett
License: GPL-2.0
LicenseUrl: https://github.com/Jackett/Jackett/blob/HEAD/LICENSE
Copyright: Copyright (C) 1989, 1991 Free Software Foundation, Inc.
CopyrightUrl: https://github.com/Jackett/Jackett/blob/master/LICENSE
ShortDescription: API Support for your favorite torrent trackers.
Description: |-
  Jackett works as a proxy server, it translates queries from apps (Sonarr, Radarr, SickRage, CouchPotato, Mylar, etc) into tracker-site-specific http queries, parses the html response, then sends results back to the requesting software.
  This allows for getting recent uploads (like RSS) and performing searches.
  Jackett is a single repository of maintained indexer scraping and translation logic - removing the burden from other apps.
Moniker: jackett
Tags:
- indexer
- p2p
- proxy
- rss
- sonarr
- torent-management
- torrent
- torrent-search-engine
- trackers
ReleaseNotes: |-
  Changes:
  - 88a9ae4 huntorrent: search all 4 browsers. resolves #10771
  - 5e71e30 add sextorrent a private site. resolves #16182
  - 3060759 Update rudub
  - 38ffba9 uhdtorrent: removed. resolves #16262
  - 98fd98d cangbaoge: leech,grabs can be missing
  - 0f5f76a huntorrent: new selectors, again
  - 7a8ffe2 phoenixproject: restore private tracker with scraping (#16266)
  This list of changes was auto generated.
ReleaseNotesUrl: https://github.com/Jackett/Jackett/releases/tag/v0.24.241
ManifestType: defaultLocale
ManifestVersion: 1.10.0
